export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_TERMINAL = 'TOGGLE_TERMINAL';
export const SECTION_FILLED = 'SECTION_FILLED';

export const SEND_MAIL = 'SEND_MAIL';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILURE = 'SEND_MAIL_FAILURE';
